### ISSUE TITLE
4.12.3 Version Update. Change app path

### ISSUE THREAD

**Issue by metalsimyaci** [davidepedrazzi/CleanMyMacX#10]
Hello,

Any chance of an update for version 4.12.3(41203.0.2212211303)?

The application path has changed for new versions. /Applications/CleanMyMac X.app

The other issue is the friend mentioned
Unfortunately, the patch for version 4.12.1 (41201.0.2211091011) did not work. If I could run it I would merge you to update the app.

Can you help me?

Thank you for the project.

**Comment by davidepedrazzi** [comment]
Updated!
It should now work with the latest version of CleanMyMac X (4.12.4)

**Comment by maziman84** [comment]
the latest is now 4.12.5, 10 February 2023

**Comment by metalsimyaci** [comment]
Thank you.
