### ISSUE TITLE
'-[CMMASLimitation isExceeded]' not found

### ISSUE THREAD

**Issue by condolar** [davidepedrazzi/CleanMyMacX#12]
Hi, running into the issue below on the final step, any ideas?

connorhastie@Connors-MacBook-Pro CleanMyMacX % sudo python3 ./patch.py
Patching /Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS...
FAILED: Function `-[CMMASLimitation isExceeded]` not found.

Thanks in advance, appreciate your work @davidepedrazzi

**Comment by abdulradcliffe** [comment]
facing the same problem on `MacOS Monterey (12.6.2)`, even after installing latest version from app store, facing same issue

**Comment by davidepedrazzi** [comment]
Updated!
It should now work with the latest version of CleanMyMac X (4.12.4)
