### ISSUE TITLE
Function names and path names are set for Clean My Mac-MAS

### ISSUE THREAD

**Issue by BrownCoatJustice** [davidepedrazzi/CleanMyMacX#13]
```
app_path = Path('/Applications/CleanMyMac-MAS.app')
binary_path = app_path.joinpath('Contents/MacOS/CleanMyMac-MAS')
```
are not the app paths for Clean My Mac X, instead,
```

app_path = Path('/Applications/CleanMyMac X.app')
binary_path = app_path.joinpath('Contents/MacOS/CleanMyMac X')

```
worked for me, but certain functions like
`[CMMASActivationManager isAppActivated]')`
still need to be changed to their correct counterparts.

**Comment by davidepedrazzi** [comment]
The path and version do not match because you downloaded the app from the website which is not yet supported.

You can download the latest version of CleanMyMac X (4.12.4) from the App Store.
