### ISSUE TITLE
Not working for CleanMyMac 4.12.6

### ISSUE THREAD

**Issue by alejomoreira** [davidepedrazzi/CleanMyMacX#14]
sudo ./patch.py
Patching /Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS...
FAILED: Function `-[CMMASActivationManager isAppActivated]` not found.

**Comment by davidepedrazzi** [comment]
Updated!
It should now work with the latest version of CleanMyMac X (4.12.6)
