### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JinXinAuzn** [davidepedrazzi/CleanMyMacX#15]
Patching /Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS...
Traceback (most recent call last):
  File "/Users/CleanMyMacX-main/./patch.py", line 91, in <module>
    main()
  File "/Users/CleanMyMacX-main/./patch.py", line 33, in main
    with open(binary_path, 'rb+') as file:
PermissionError: [Errno 1] Operation not permitted: '/Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS'

**Comment by sleepdefic1t** [comment]
Did you `chmod u+x patch.py` first?

**Comment by davidepedrazzi** [comment]
Have you tried this? https://github.com/davidepedrazzi/CleanMyMacX/issues/7#issuecomment-1366008464
