### ISSUE TITLE
Not open all features

### ISSUE THREAD

**Issue by telepati** [davidepedrazzi/CleanMyMacX#16]
Hi, I tried your script. And its working on the main app but it's not working on the menu bar items. Am I doing something wrong?

I download the MAS version from Appstore. And I followed the how-to-use directions. And got the expected output without anything wrong. I am on an Intel machine by the way. I didn't start the app before the use script. I tried twice and uninstall it fully with leftovers but still, it did not unlock the menu bar features.

Terminal Output
`
Patching /Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS...
Patching /Applications/CleanMyMac-MAS.app/Contents/Library/LoginItems/CleanMyMac-MAS Menu.app/Contents/MacOS/CleanMyMac-MAS Menu...
Re-signing /Applications/CleanMyMac-MAS.app...
/Applications/CleanMyMac-MAS.app: replacing existing signature
/Applications/CleanMyMac-MAS.app: valid on disk
/Applications/CleanMyMac-MAS.app: satisfies its Designated Requirement
Enjoy!
`

<img width="476" alt="Screenshot 2023-03-14 at 17 50 34" src="https://user-images.githubusercontent.com/3812286/225040262-1a0c4b49-2b0b-449b-a262-c333a5fece2d.png">

**Comment by davidepedrazzi** [comment]
You should carefully read the README file before opening an issue.

**Comment by Dakegege** [comment]
I have the same problem as you, I did it completely according to the README file.

**Comment by telepati** [comment]
> I have the same problem as you, I did it completely according to the README file.

This is not a problem. He clearly states on the readme, we just missed that.

Unlock **(almost)** all CleanMyMac X's features for free!

**Comment by davidepedrazzi** [comment]
Thank God, someone who can read. It is also specified in the to-do list: `Hide 'Unlock Full Version' button in menu`.

Not an issue.
