### ISSUE TITLE
new to this, password help

### ISSUE THREAD

**Issue by Stam0916** [davidepedrazzi/CleanMyMacX#17]
so I get to the  sudo ./patch.py step, hit enter, and it asks for a password. am I missing it somewhere in the steps where it says what it is ?

**Comment by davidepedrazzi** [comment]
Simply enter the login password for your macOS account.

**Comment by Stam0916** [comment]
im an idiot lol. thanks for the knock on the side of the head hahah

**Comment by davidepedrazzi** [comment]
Welcome to the club! ;)
