### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by quixotic120** [davidepedrazzi/CleanMyMacX#20]
4.13.2, breaks patch

xxxxx CleanMyMacX % sudo ./patch.py
Patching /Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS...
FAILED: Function `-[CMMASActivationManager isAppActivated]` not found.

**Comment by henryyds** [comment]
Same here, in the latest version

**Comment by telepati** [comment]
Read this;

https://github.com/davidepedrazzi/CleanMyMacX/issues/19

**Comment by henryyds** [comment]
I deleted everything still the same problem.

**Comment by nautilusserver** [comment]
Same here wih the latest version on Intel

**Comment by davidepedrazzi** [comment]
Thank you for the reports. I am not home right now but I will release a patch in the next hours.

**Comment by nautilusserver** [comment]
Thank you!

**Comment by davidepedrazzi** [comment]
Updated!
It should now work with the latest version of CleanMyMac X (4.13.2)

**Comment by henryyds** [comment]
Thank you so much. Working

**Comment by nautilusserver** [comment]
Thanks! works flawlessly!

**Comment by bliss95** [comment]
Unlock Full Version label in Menu

**Comment by henryyds** [comment]
Not working again for the latest update
