### ISSUE TITLE
Permission error while running the sudo command

### ISSUE THREAD

**Issue by saurabhudavant21** [davidepedrazzi/CleanMyMacX#7]
Here is the error I am getting. Tried deleting and reinstalling the application already, didn't work. Please help

Patching /Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS...
Traceback (most recent call last):
  File "/Users/saurabhudavant/Downloads/CleanMyMacX/./patch.py", line 91, in <module>
    main()
  File "/Users/saurabhudavant/Downloads/CleanMyMacX/./patch.py", line 33, in main
    with open(binary_path, 'rb+') as file:
PermissionError: [Errno 1] Operation not permitted: '/Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS'

**Comment by saurabhudavant21** [comment]
@davidepedrazzi

**Comment by davidepedrazzi** [comment]
Please read the error and make sure you follow the instructions before opening a new issue.

It’s `sudo ./patch.py` not `./patch.py`.

**Comment by saurabhudavant21** [comment]
I have followed exactly the same instructions mentioned and I am still getting this error. I am not very familiar with using Terminal and hence cant understand what wrong here.

saurabhudavant@Saurabhs-Personal-Macbook-Pro ~ % cd downloads
saurabhudavant@Saurabhs-Personal-Macbook-Pro downloads % git clone https://github.com/davidepedrazzi/CleanMyMacX.git
Cloning into 'CleanMyMacX'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 39 (delta 16), reused 29 (delta 10), pack-reused 0
Receiving objects: 100% (39/39), 7.82 KiB | 2.61 MiB/s, done.
Resolving deltas: 100% (16/16), done.
saurabhudavant@Saurabhs-Personal-Macbook-Pro downloads % cd CleanMyMacX
saurabhudavant@Saurabhs-Personal-Macbook-Pro CleanMyMacX % chmod u+x patch.py
saurabhudavant@Saurabhs-Personal-Macbook-Pro CleanMyMacX % sudo ./patch.py
Password:
Patching /Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS...
Traceback (most recent call last):
  File "/Users/saurabhudavant/Downloads/CleanMyMacX/./patch.py", line 91, in <module>
    main()
  File "/Users/saurabhudavant/Downloads/CleanMyMacX/./patch.py", line 33, in main
    with open(binary_path, 'rb+') as file:
PermissionError: [Errno 1] Operation not permitted: '/Applications/CleanMyMac-MAS.app/Contents/MacOS/CleanMyMac-MAS'
saurabhudavant@Saurabhs-Personal-Macbook-Pro CleanMyMacX %

**Comment by davidepedrazzi** [comment]
Sorry for misunderstanding.
I tried with the latest version of CleanMyMac X (4.12.2) on macOS Ventura 13.1 and it worked fine.

Please add me on Discord:
N30#4255

**Comment by Jedeiah** [comment]
macos 13.1 系统设置->隐私与安全性->App管理->终端（允许修改删除其他程序）。

**Comment by davidepedrazzi** [comment]
For those who do not understand Chinese,

System Settings > Privacy & Security > App Management > Add your Terminal to the list (A new security feature in macOS Ventura)

Please let me know if this works for you.

**Comment by saurabhudavant21** [comment]
great thanks to @Jedeiah and @davidepedrazzi for the help...this is sorted! cheers

**Comment by davidepedrazzi** [comment]
Thank you for sharing your experience,
I hope this can help someone else in the future. ^^
