### ISSUE TITLE
还是提示“试用配额已用尽”

### ISSUE THREAD

**Issue by Jedeiah** [davidepedrazzi/CleanMyMacX#8]
问题描述：
1已经超过免费试用的cleanmymacx
2下载执行楼主的脚本文件后，输出正确。
3打开cleanmymacx可以使用一次，再次使用cleanmymacx清理文件，就又提示不能免费试用。
--- 这怎么解决？

**Comment by davidepedrazzi** [comment]
Is anyone else facing the same issue?

**Comment by Jedeiah** [comment]
> 还有其他人面临同样的问题吗？

我的Mac是m1系列芯片，cleanmymacx是从app store下载的。

**Comment by davidepedrazzi** [comment]
Apple silicon is not supported.
